# Generated by Django 3.0.6 on 2020-06-06 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='probobj',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_tag', models.CharField(default='unnamed', max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('p_desc', models.TextField()),
                ('p_in', models.CharField(default='', max_length=200)),
                ('p_out', models.CharField(default='', max_length=200)),
                ('p_const', models.CharField(default='', max_length=200)),
                ('p_exin', models.CharField(default='', max_length=200)),
                ('p_exout', models.CharField(default='', max_length=200)),
                ('p_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('p_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
