# Generated by Django 3.0.6 on 2020-06-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probobj',
            name='p_code',
            field=models.TextField(default=''),
        ),
    ]
